# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMerezhka():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_merezhka(self):
    self.driver.get("https://merezhka.com/")
    self.driver.set_window_size(1280, 572)
    self.driver.execute_script("window.scrollTo(0,200)")
    self.driver.find_element(By.CSS_SELECTOR, ".cs-product-groups-gallery__item:nth-child(7) .cs-product-groups-gallery__image-link").click()
    self.driver.execute_script("window.scrollTo(0,6)")
    self.driver.find_element(By.CSS_SELECTOR, ".cs-online-edit:nth-child(5) .cs-product-gallery__image-link").click()
    self.driver.find_element(By.LINK_TEXT, "Жіночі вишиванки").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cs-online-edit:nth-child(10) .cs-product-gallery__image-link").click()
    self.driver.find_element(By.LINK_TEXT, "Жіночі вишиті водолазки").click()
    self.driver.execute_script("window.scrollTo(0,400)")
    self.driver.find_element(By.CSS_SELECTOR, ".cs-online-edit:nth-child(9) .cs-product-gallery__image-link").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cs-pictures__cell:nth-child(3) > .cs-pictures__img-wrap:nth-child(2) > .cs-pictures__img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ROverlay__closeButton--3lncy").click()
  
