# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestrozetka():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testrozetka(self):
    self.driver.get("https://rozetka.com.ua/")
    self.driver.set_window_size(1280, 572)
    element = self.driver.find_element(By.CSS_SELECTOR, ".main-notification__thumbnail")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.NAME, "search").click()
    self.driver.find_element(By.NAME, "search").send_keys("фен")
    self.driver.find_element(By.CSS_SELECTOR, ".button_color_green > font > font").click()
    self.driver.find_element(By.LINK_TEXT, "Фен для волос Jimmy F6 Purple").click()
    element = self.driver.find_element(By.LINK_TEXT, "Фен для волос Jimmy F6 Purple")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".product-about__block:nth-child(1) .product-seller__rating:nth-child(1)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
  
