# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestKarandash():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_karandash(self):
    self.driver.get("https://karandashi.in.ua/ua/")
    self.driver.set_window_size(1280, 572)
    self.driver.find_element(By.LINK_TEXT, "Контакти").click()
    self.driver.execute_script("window.scrollTo(0,700)")
    self.driver.find_element(By.LINK_TEXT, "Про компанію").click()
    self.driver.execute_script("window.scrollTo(0,6)")
    self.driver.execute_script("window.scrollTo(0,226.6666717529297)")
    self.driver.execute_script("window.scrollTo(0,700)")
    self.driver.execute_script("window.scrollTo(0,1000)")
    self.driver.find_element(By.LINK_TEXT, "Доставка та оплата").click()
    self.driver.execute_script("window.scrollTo(0,163.3333282470703)")
    self.driver.execute_script("window.scrollTo(0,600)")
    self.driver.find_element(By.LINK_TEXT, "Товари").click()
    self.driver.execute_script("window.scrollTo(0,173.3333282470703)")
    self.driver.execute_script("window.scrollTo(0,600)")
    self.driver.find_element(By.CSS_SELECTOR, ".b-product-groups-gallery__item:nth-child(8) .b-product-groups-gallery__image").click()
    self.driver.execute_script("window.scrollTo(0,358.6666564941406)")
    self.driver.find_element(By.CSS_SELECTOR, ".b-product-groups-gallery__item:nth-child(3) .b-product-groups-gallery__image").click()
    self.driver.execute_script("window.scrollTo(0,300)")
    self.driver.find_element(By.CSS_SELECTOR, ".b-online-edit:nth-child(2) .b-product-list__image").click()
  
